### ISSUE TITLE
cant import in swift

### ISSUE THREAD

**Issue by mirzadelic** [mrackwitz/MRProgress#101]
I can't import like `import MRProgress` in swift.
```
No such module 'MRProgress'
```

I installed it from pod. (`pod 'MRProgress'`)

What is problem here?

**Comment by mirzadelic** [comment]
I don't know if this is happening only to me?

**Comment by mrackwitz** [comment]
Which version of CocoaPods do you use? Do you have `use_frameworks!` in your Podfile for the target you integrate?

**Comment by mirzadelic** [comment]
I don't use `use_frameworks!` becouse GoogleCloudMessages doesn't support it.
That is problem?

**Comment by mrackwitz** [comment]
Otherwise you will need to import it by `#import <MRPRogress/MRProgress.h>` in your bridging header.

**Comment by mirzadelic** [comment]
How can i import it in bridging header, any steps?

**Comment by mrackwitz** [comment]
https://bohemianpolymorph.wordpress.com/2014/07/11/manually-adding-a-swift-bridging-header/

**Comment by mirzadelic** [comment]
I did this, but still same error: `No such module 'MRProgress'`.
What i did:
1. installed from pod without use_framework!
2. created file MyApp-Bridging-Header.h with content:
```
//
//  MyApp-Bridging-Header.h
//  MyApp
//
//  Created by Mirza Delic on 7/1/15.
//  Copyright (c) 2015 Mirza Delic. All rights reserved.
//

#ifndef MyApp_MyApp_Bridging_Header_h
#define MyApp_MyApp_Bridging_Header_h

#import <MRPRogress/MRProgress.h>

#endif
```
3. in Build Settings `Objective-C Bridging Header` location 'MyApp/MyApp-Bridging-Header.h`.
4. then i build and still same error.


What am i doing wrong?

**Comment by mrackwitz** [comment]
Did you also removed `import MRProgress` from your Swift code?

**Comment by mirzadelic** [comment]
Ohh, i forgot that, thanks.
