### ISSUE TITLE
[Question] Removing the white HUD from the MRProgressOverlayView

### ISSUE THREAD

**Issue by ldantona** [mrackwitz/MRProgress#104]
Would it be possible to remove the white rounded box and just have the dimmed overlay with the circle animation above?

Many thanks,
DAN

**Comment by mrackwitz** [comment]
There is no direct public API to achieve that. But you could e.g. subclass `MRProgressOverlayView` and overwrite [`createBlurView`](https://github.com/mrackwitz/MRProgress/blob/master/src/Components/MRProgressOverlayView.h#L131-L138) to return `nil` instead of an actual view.
