### ISSUE TITLE
Crash when use MRNavigationBarProgressView iOS 9

### ISSUE THREAD

**Issue by nadagamal** [mrackwitz/MRProgress#110]
Hi , 
Thanks a lot for your progress :) . but I have a crash when add progress to navigation controller . 
    
    [[MRNavigationBarProgressView progressViewForNavigationController:self.navigationController]
     setProgressWithDownloadProgressOfTask:task animated:YES];

[SGProgressView setProgressWithDownloadProgressOfTask:animated:]: unrecognized selector sent to instance 0x7f88b0f21870
2015-09-20 12:37:57.532  *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SGProgressView setProgressWithDownloadProgressOfTask:animated:]: unrecognized selector sent to instance 0x7f88b0f21870'

**Comment by mrackwitz** [comment]
Seems like you have another navigation bar progress view component included in your project. Because this contains no class `SGProgressView`, or is that your own subclass of `MRNavigationBarProgressView`?
