### ISSUE TITLE
Hide BlurView and Label in MRProgressOverlayView

### ISSUE THREAD

**Issue by ftp27** [mrackwitz/MRProgress#114]
Hello.
I'm trying to use MRProgressOverlayView+AFNetworking on UIImageView for display the progress of uploading image. But BlurView and Label look are incorrect in this situation. How can I hide this UIViews?

![2015-12-24 17 18 32](https://cloud.githubusercontent.com/assets/579162/11995493/6e82539a-aa62-11e5-8033-fd3fdcfb5c3d.png)

**Comment by mrackwitz** [comment]
I'd suggest that you can use `MRCircularProgressView` directly, if you don't want to have the blurred background and the label. It supports the AFNetworking integration as well.

**Comment by ftp27** [comment]
Thanks! All works
