### ISSUE TITLE
Is it possible to show indetermination view without overlay, so users can interact with some special logic views?

### ISSUE THREAD

**Issue by melote** [mrackwitz/MRProgress#121]
Sometimes we want to show some indetermination views to tell user something is loading but you can interact with the app.

**Comment by mrackwitz** [comment]
You can just use the indeterminate activity indicator separately without the full dialog. Alternatively you can show the dialog just above a specific view, which doesn't hide the controls, your users should be still able to interact with.

**Comment by melote** [comment]
Thanks for your suggestions. I will try that.
