### ISSUE TITLE
App crashes when trying to display 

### ISSUE THREAD

**Issue by dhint4** [mrackwitz/MRProgress#84]
In my view controller, when a button is pushed, I have a method that calls for a progress view to be displayed like this:

```objective-c
 [MRProgressOverlayView showOverlayAddedTo:self.view title:@"Uploading..." mode:MRProgressOverlayViewModeIndeterminate animated:true];
```

As soon as that method is called, the app crashed and gives me an error in the console of:
```
Assertion failed: (transform_is_valid(m)), function CGPathRef CGPathCreateWithRect(CGRect, const CGAffineTransform *), file Paths/CGPath.cc, line 179.
```

I am not sure what to do. Any help would be greatly appreciated!

Thanks

**Comment by dhint4** [comment]
Thanks for responding but I believe I figured out the problem. I was trying to display (for testing purposes) in the init method of the view instead of waiting till the view was completely loaded. This was the reason for the crashing. It is now working and all I can say is that this library is absolutely beautiful. Awesome work! :+1:

**Comment by mrackwitz** [comment]
Thanks for leaving your feedback!
