### ISSUE TITLE
App crashes when trying to display 

### ISSUE THREAD

**Issue by dhint4** [mrackwitz/MRProgress#88]
Hey again! 

I posted an exact same issue a few weeks ago but I am getting another error.

Here is my method call:

```
-(void)viewDidAppear:(BOOL)animated{
     [MRProgressOverlayView showOverlayAddedTo:_inspectedView.window title:@"Uploading..." mode:MRProgressOverlayViewModeDeterminateCircular animated:true];
}
```

This is what I get back in return: The compiler throws a breakpoint in the snapshot method of MRBlurView.m

```
// Translate to draw at the absolute origin of the receiver
    CGContextTranslateCTM(context, -origin.x, -origin.y);
    
    // Draw the window
    [window.layer renderInContext:context]; <------------ This is where the breakpoint occurs
    
    // Capture the image and exit context
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
```

I also get this in the console:
>Assertion failed: (transform_is_valid(m)), function CGPathRef CGPathCreateWithRect(CGRect, const CGAffineTransform *), file Paths/CGPath.cc, line 179.

Any help would be appreciated!

Thanks

**Comment by mrackwitz** [comment]
One thing, which directly jumps in my eyes is, you either forgot to call the super method, or you removed it from the condensed sample code, you posted here:
```diff
 -(void)viewDidAppear:(BOOL)animated{
+    [super viewDidAppear:YES];
     [MRProgressOverlayView showOverlayAddedTo:_inspectedView.window title:@"Uploading..." mode:MRProgressOverlayViewModeDeterminateCircular animated:true];
```
Is `_inspectedView` always initialized, when this happens?

**Comment by dhint4** [comment]
That was indeed the case! Sorry for not reporting back earlier!

**Comment by mrackwitz** [comment]
Still thanks for the feedback!
