### ISSUE TITLE
Crash on MRProgreessOverlayView.showOverlayAddedTo

### ISSUE THREAD

**Issue by dcgoss** [mrackwitz/MRProgress#90]
Getting error that crashes app: `2015-01-24 16:50:04.563 Pickle[24864:6627769] -[UIImage mr_applyBlurWithRadius:tintColor:saturationDeltaFactor:maskImage:]: unrecognized selector sent to instance 0x7f8255323820`

After calling: `MRProgressOverlayView.showOverlayAddedTo(self.view.window, animated: true)`.

The progress view shows up fine, but it appears that as soon as it tries to make its background an opaque white it is crashing.

The offending line of code that Xcode is highlighting on the crash: `image = [image mr_applyBlurWithRadius:30.0 tintColor:[UIColor colorWithWhite:0.97 alpha:0.82] saturationDeltaFactor:1.0 maskImage:nil];`
Which is from the `MRBlurView` class.

**Comment by mrackwitz** [comment]
How did you integrated the library in your project?

**Comment by dcgoss** [comment]
I used CocoaPods.

**Comment by mrackwitz** [comment]
Can you check that `OTHER_LD_FLAGS` include `$(inherited)`. See #10.
Did you saw any warnings about that on `pod install`?

**Comment by dcgoss** [comment]
Adding $(inherited) worked! Thank you!

**Comment by mrackwitz** [comment]
:+1:
