### ISSUE TITLE
MRProgress.h

### ISSUE THREAD

**Issue by mworsnop** [mrackwitz/MRProgress#92]
The MRProgress.h is missing from the master zip.  Not sure what else is missing as I cant go any further. Any ideas what I did wrong?

**Comment by mrackwitz** [comment]
Are you sure? I just checked it out myself and the "MRProgress.h" was present were expected.

**Comment by mworsnop** [comment]
I just unzipped the the master zip and there is no MRProgress.h  Maybe I
downloaded the wrong zip? I didn¹t run anything, just downloaded and
unzipped. 


From:  Marius Rackwitz <notifications@github.com>
Reply-To:  mrackwitz/MRProgress
<reply+009c093c00d96029079348b8d5f2a0babce8c77b3bfe7e4192cf0000000110f097cd9
2a169ce0366727e@reply.github.com>
Date:  Monday, February 9, 2015 at 7:44 AM
To:  mrackwitz/MRProgress <MRProgress@noreply.github.com>
Cc:  Mark Worsnop <mark@worsnop.com>
Subject:  Re: [MRProgress] MRProgress.h (#92)


Are you sure? I just checked it out myself and the "MRProgress.h" was
present were expected.

‹
Reply to this email directly or view it on GitHub
<https://github.com/mrackwitz/MRProgress/issues/92#issuecomment-73530358> .

**Comment by mrackwitz** [comment]
Just to be sure: Did you take a look into the `src` directory? If not, you should be able to find it there.

**Comment by mworsnop** [comment]
I tried running the example Xcode workspace.  First it tries to do something
with pod which I haven¹t used before.  I disabled that so I could try and
compile. 

I did find the .h in the src file.

However trying to compile the example its says can¹t find:

#import ³AFNetworking.h"



Then it tries to load these but there is only one file in the MRProgress
directory



#import <MRProgress/MRActivityIndicatorView.h>

#import <MRProgress/MRCircularProgressView.h>

#import <MRProgress/MRProgressOverlayView.h>


From:  Marius Rackwitz <notifications@github.com>
Reply-To:  mrackwitz/MRProgress
<reply+009c093c2a38155eebe352d337a233f7fc9f4a24b571c9b292cf0000000110f099eb9
2a169ce0366727e@reply.github.com>
Date:  Monday, February 9, 2015 at 7:53 AM
To:  mrackwitz/MRProgress <MRProgress@noreply.github.com>
Cc:  Mark Worsnop <mark@worsnop.com>
Subject:  Re: [MRProgress] MRProgress.h (#92)


Just to be sure: Did you take a look into the src directory? If not, you
should be able to find it there.

‹
Reply to this email directly or view it on GitHub
<https://github.com/mrackwitz/MRProgress/issues/92#issuecomment-73532179> .

**Comment by mrackwitz** [comment]
Sorry Mark, forget to address this. The Example project is integrated with [CocoaPods](/CocoaPods/CocoaPods). As the Pods directory isn't in the repo, you would need to run `pod install` locally to try it out.
