### ISSUE TITLE
Cannot install MRProgress/AFNetworking with latest AFNetworking using CocoaPods

### ISSUE THREAD

**Issue by klandor** [mrackwitz/MRProgress#99]
When I tried to install MRProgress/AFNetworking with AFNetworking 2.5.2 using CocoaPods, I got following message:
```
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `AFNetworking/UIKit (= 2.5.2)` required by `AFNetworking (2.5.2)`
- `AFNetworking/UIKit (= 2.3.1)` required by `MRProgress/AFNetworking/Base (0.6.0)`
```
Looks like podspec issue?

**Comment by mrackwitz** [comment]
The internal dependency of the podspec was outdated. I merged #97 to prevent that happening again and I'm releasing an update over CocoaPods.

**Comment by klandor** [comment]
Great!

**Comment by smarteletec-devs** [comment]
Hello Guys, 

With the version AFNetworking (2.6.3) the same error is back again when I try to integrate MRProgress with AFNetworking.

Any possible workaround for this!

and thanks for the this great library :).
